site_name: AeroKit
repo_name: aerokit
repo_url: https://github.com/jgressier/aerokit
edit_uri: ''  #disables edit button

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  # language: en
  # features:
  #   - navigation.tabs

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - User Guide:
    - User Guide: userguide.md
    - aero.Isentropic: userguide/aero.Isentropic.md
    - aero.MassFlow: userguide/aero.MassFlow.md
    - aero.ShockWave:  userguide/aero.ShockWave.md
  - Examples: 
    - Examples: examples.md
    - aero.Isentropic: examples/aero.Isentropic.ipynb
    - aero.MassFlow: examples/aero.MassFlow.ipynb
    - aero.ShockWave: examples/aero.ShockWave.ipynb
    - instance.riemann: examples/instance.riemann.ipynb
  - Change log: changelog.md
  - About: about.md

plugins:
  - search
  - include-markdown
  - mkdocs-jupyter:
      execute: True
      include_source: False
  - exclude:
      glob:
        - "requirements.txt"
        - "*/.ipynb_checkpoints"
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: false
            show_source: true
            show_category_heading: true
          selection:
            #docstring_style: "restructured-text" # default is "google"
            filters:
              - "!^_"  # exlude all members starting with _
      watch:
        - aerokit